import { TestConfig } from '../types'

export const TEST_CONFIGS: TestConfig[] = [
  {
    id: 'dead-pixel',
    name: '坏点检测',
    description: '通过纯色背景检测屏幕坏点、亮点、暗点',
    icon: 'Grid3x3',
    path: '/screen-test/dead-pixel',
    category: 'pixel',
  },
  {
    id: 'refresh-rate',
    name: '刷新率测试',
    description: '实时检测屏幕刷新率和帧时间',
    icon: 'Gauge',
    path: '/screen-test/refresh-rate',
    category: 'motion',
  },
  {
    id: 'pwm-flicker',
    name: 'PWM频闪检测',
    description: '检测屏幕是否存在低频PWM频闪',
    icon: 'Zap',
    path: '/screen-test/pwm-flicker',
    category: 'display',
  },
  {
    id: 'color-accuracy',
    name: '色彩准确度',
    description: '24色ColorChecker色卡测试',
    icon: 'Palette',
    path: '/screen-test/color-accuracy',
    category: 'color',
  },
  {
    id: 'response-time',
    name: '响应时间测试',
    description: '通过拖影测试评估屏幕响应速度',
    icon: 'Timer',
    path: '/screen-test/response-time',
    category: 'motion',
  },
  {
    id: 'uniformity',
    name: '亮度均匀性',
    description: '检测屏幕各区域亮度是否均匀',
    icon: 'Sun',
    path: '/screen-test/uniformity',
    category: 'display',
  },
  {
    id: 'color-gamut',
    name: '色域覆盖',
    description: '测试sRGB/P3色域覆盖能力',
    icon: 'Rainbow',
    path: '/screen-test/color-gamut',
    category: 'color',
  },
  {
    id: 'hdr',
    name: 'HDR测试',
    description: '测试高动态范围显示效果',
    icon: 'Contrast',
    path: '/screen-test/hdr',
    category: 'display',
  },
  {
    id: 'burn-in',
    name: 'OLED烧屏检测',
    description: '检测OLED屏幕老化/烧屏痕迹',
    icon: 'Flame',
    path: '/screen-test/burn-in',
    category: 'pixel',
  },
  {
    id: 'viewing-angle',
    name: '可视角度测试',
    description: '利用陀螺仪测试不同角度显示效果',
    icon: 'Move3d',
    path: '/screen-test/viewing-angle',
    category: 'display',
  },
]
